version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6380:6379"
